name: Run CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - names: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./taskmanager

      - name: Run tests
        run: npm run test
        working-directory: ./taskmanager

  linter:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v3
      - names: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./taskmanager

      - name: Run linter
        run: npm run lint
        working-directory: ./taskmanager



